package de.kartellamt.db.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * ProjectGroup generated by hbm2java
 */
@Entity
@Table(name = "project_group", catalog = "gisnet")
@NamedQuery(name="ProjectGroup.findAll", query="SELECT g FROM ProjectGroup g ") 

public class ProjectGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	
	private Integer id;
	private String project;
	private String gngroup;

	public ProjectGroup() {
	}

	public ProjectGroup(String project, String gngroup) {
		this.project = project;
		this.gngroup = gngroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project", nullable = false, length = 45)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "gngroup", nullable = false, length = 45)
	public String getGngroup() {
		return this.gngroup;
	}

	public void setGngroup(String gngroup) {
		this.gngroup = gngroup;
	}
	
	
	@Override
	public String toString() {
		return this.getProject();
	}

}

